### PR TITLE
Fix markdown table.

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus <achim.kraus@cloudcoap.net>

### CODE REVIEW

**Comment by boaks** [comment]
AFAIK, if you view the table on github directly [draft-ietf-tls-dtls-rrc.md](https://github.com/tlswg/dtls-rrc/blob/master/draft-ietf-tls-dtls-rrc.md#new-tls-contenttype), it's broken (Firefox, Opera). 
If the second line is adjusted, it's shown proper.

**Comment by thomas-fossati** [comment]
Ah, ok! Note though that the important thing for us is the rendering obtained via kdrfc / xml2rfc.  Have you tried locally to see if the change displays correctly with those tools?

**Comment by boaks** [comment]
> Have you tried locally to see if the change displays correctly with those tools?

No, I will do that on Monday.

**Comment by boaks** [comment]
> kdrfc / xml2rfc

Is there a link to download or package to install?

**Comment by boaks** [comment]
[xml2rfc](https://pypi.org/project/xml2rfc/)

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> breathe 4.25.1 requires Sphinx<3.4,>=3.0, but you have sphinx 3.4.1 which is incompatible.

**Comment by thomas-fossati** [comment]
> > kdrfc / xml2rfc
> 
> Is there a link to download or package to install?

See https://github.com/martinthomson/i-d-template/blob/main/doc/SETUP.md for a pretty complete setup.

**Comment by boaks** [comment]
```
pip3 install --user xml2rfc
```

works. Is there a guide how to execute it?

**Comment by boaks** [comment]
> Error: Unable to parse the XML document: draft-ietf-tls-dtls-rrc.md

Is there a guide, which tools are required, to convert a .md file and how to install and run them?

**Comment by boaks** [comment]
kramdown-rfc requires ruby ...

May experience with such "import all tools of the world" is, 
that my PC stops to work for the things which are important for me.

Maybe there is a docker image with the tools?

**Comment by thomas-fossati** [comment]
> kramdown-rfc requires ruby ...
> 
> May experience with such "import all tools of the world" is, that my PC stops to work for the things which are important for me.
> 
> Maybe there is a docker image with the tools?

you can try this: https://github.com/larseggert/i-d-toolchain

or this: https://github.com/martinthomson/i-d-template/tree/main/docker/action

**Comment by boaks** [comment]
I applied [i-d-toolchain via web ui](https://github.com/larseggert/i-d-toolchain#via-a-web-ui). It works with the changed table as well.

I don't insist in this change, though the "i-d-toolchain" doesn't depend on it, 
but for me it is more compliant to [markdown tables](https://www.markdownguide.org/extended-syntax/#tables).

**Pull request merged**
